name: time_tracker
description: A new Flutter project.


publish_to: "none" 













version: 1.0.2+5

environment:
  sdk: ">=3.1.0 <4.0.0"







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  ndialog: ^4.3.1
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  adaptive_theme: ^3.3.1
  animations: ^2.0.8
  countdown_progress_indicator: ^0.1.2
  android_alarm_manager_plus: ^3.0.2
  retrofit: ^4.0.1
  logger: ^2.0.2
  responsive_sizer: ^3.2.0
  duration_picker: ^1.1.1
  stop_watch_timer: ^3.0.2
  duration: ^3.0.12
  intl: ^0.18.1
  fl_chart: ^0.64.0
  syncfusion_flutter_charts: ^23.1.39
  flutter_bloc: ^8.1.5
  go_router: ^13.2.2
  fl_toast: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Screenshot 2023-10-11 131322 (1).png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/Screenshot 2023-10-11 131322 (1).png"
  adaptive_icon_background: "#ffffff"
  
  
  
  
  
  
  
  
  
  
  
  
  
  





flutter:
  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
